### ISSUE TITLE
Constructor should detect server:port format automatically

### ISSUE THREAD

**Issue by singiamtel** [PartMan7/PS-Client#15]
When ``port`` is ommited in the constructor we can just use whatever port ``server`` defines, e.g. ``..., server: 'myserver:1234'``

Currently only ``..., server: 'myserver', port: 1234`` format is allowed

**Comment by PartMan7** [comment]
Added in https://github.com/PartMan7/PS-Client/commit/ee0dbd3cf8cf8ad2f1f2b0c063681b739497fc10
